//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_box.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int OpinionID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int ProductID { get; set; }
        public string OpinionTitle { get; set; }
        public string OpinionContent { get; set; }
        public int OpinionStatus { get; set; }
        public string OpinionDateTime { get; set; }
        public string OpinionFeedback { get; set; }
        public string OpinionFeedbackTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
