//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_box.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalItemImage
    {
        public int OptionalItemImageID { get; set; }
        public int ProductID { get; set; }
        public string OptionalItemImageLocation { get; set; }
        public Nullable<int> OptionalItemImageWidth { get; set; }
        public Nullable<int> OptionalItemImageTop { get; set; }
        public Nullable<int> OptionalItemImageLeft { get; set; }
        public Nullable<int> OptionalItemImageZ { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
