//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_box.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int OpinionID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int ProductID { get; set; }
        public string OpinionTitle { get; set; }
        public string OpinionContent { get; set; }
        public int OpinionStatus { get; set; }
        public string OpinionDateTime { get; set; }
        public string OpinionFeedback { get; set; }
        public string OpinionFeedbackTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
